[build]
  command = "npm run build"
  publish = ".next"
  cache = false

[build.environment]
  NODE_ENV = "production"
  # Disable caching for Prisma
  PRISMA_DISABLE_CACHE = "true"
  NODE_VERSION = "21.7.3"


